// Naming sampler (spec 9.5): a tiny C# tokenizer that classifies class-scope field declarations, plus the
// brace, namespace and [SerializeField] shares, and the .editorconfig rules that override the sample.
import { compareOrdinal } from './fs-view.js';

export const MAX_NAMING_SAMPLE_FILES = 400;
export const MAX_NAMING_FILE_BYTES = 300 * 1024;
export const MIN_NAMING_SAMPLE = 30;
export const DOMINANT_SHARE = 0.65;
export const MAX_NAMING_FOLDERS = 5;

/** @typedef {'privateInstance' | 'privateStatic' | 'constants'} NamingCategory */

export const NAMING_CATEGORIES = Object.freeze(/** @type {NamingCategory[]} */ (['privateInstance', 'privateStatic', 'constants']));

export const STYLE_LABELS = Object.freeze({
  m_camel: 'm_camelCase',
  m_Pascal: 'm_PascalCase',
  s_camel: 's_camelCase',
  s_Pascal: 's_PascalCase',
  k_Pascal: 'k_PascalCase',
  k_camel: 'k_camelCase',
  _camel: '_camelCase',
  camel: 'camelCase',
  Pascal: 'PascalCase',
  UPPER_SNAKE: 'UPPER_SNAKE_CASE',
  other: 'other',
  mixed: 'mixed',
});

const MODIFIERS = new Set([
  'public', 'private', 'protected', 'internal', 'file', 'static', 'readonly', 'const', 'volatile', 'new',
  'unsafe', 'extern', 'fixed', 'required', 'event', 'abstract', 'virtual', 'override', 'sealed', 'partial', 'async',
]);

// A statement holding one of these is not a field declaration.
const NON_FIELD_KEYWORDS = new Set(['delegate', 'operator', 'this', 'base', 'using', 'namespace', 'return', 'class', 'struct', 'interface', 'enum', 'record', 'implicit', 'explicit']);

const TYPE_KEYWORDS = new Set(['class', 'struct', 'interface', 'record', 'enum']);

const GENERATED_HEADER = /<auto-?generated|this (code|file) (was|is) (auto-?)?generated|generated by a tool/i;

/**
 * @typedef {object} Token
 * @property {'ident' | 'punct' | 'number'} type
 * @property {string} value
 * @property {number} line
 */

/**
 * Strings, comments, char literals and preprocessor lines never reach the token stream, so a `{` in a string
 * cannot unbalance the scopes.
 * @param {string} text
 * @returns {Token[]}
 */
export function tokenizeCSharp(text) {
  /** @type {Token[]} */
  const tokens = [];
  let index = 0;
  let line = 1;
  let atLineStart = true;
  while (index < text.length) {
    const char = text[index];
    if (char === '\n') {
      line += 1;
      index += 1;
      atLineStart = true;
      continue;
    }
    if (char === ' ' || char === '\t' || char === '\r') {
      index += 1;
      continue;
    }
    if ((char === '#' && atLineStart) || (char === '/' && text[index + 1] === '/')) {
      index = endOfLine(text, index);
      continue;
    }
    if (char === '/' && text[index + 1] === '*') {
      const close = text.indexOf('*/', index + 2);
      const end = close === -1 ? text.length : close + 2;
      line += countNewlines(text, index, end);
      index = end;
      atLineStart = false;
      continue;
    }
    atLineStart = false;
    if (isStringStart(text, index)) {
      const end = skipStringLiteral(text, index);
      line += countNewlines(text, index, end);
      index = end;
      continue;
    }
    if (char === "'") {
      const end = skipCharLiteral(text, index);
      line += countNewlines(text, index, end);
      index = end;
      continue;
    }
    if (isIdentifierStart(char) || (char === '@' && isIdentifierStart(text[index + 1] ?? ''))) {
      const start = char === '@' ? index + 1 : index;
      let end = start;
      while (end < text.length && isIdentifierPart(text[end])) end += 1;
      tokens.push({ type: 'ident', value: text.slice(start, end), line });
      index = end;
      continue;
    }
    if (char >= '0' && char <= '9') {
      let end = index;
      while (end < text.length && /[0-9A-Za-z_.]/.test(text[end])) end += 1;
      tokens.push({ type: 'number', value: text.slice(index, end), line });
      index = end;
      continue;
    }
    const two = text.slice(index, index + 2);
    if (TWO_CHAR_PUNCT.has(two)) {
      tokens.push({ type: 'punct', value: two, line });
      index += 2;
      continue;
    }
    tokens.push({ type: 'punct', value: char, line });
    index += 1;
  }
  return tokens;
}

// `<` and `>` stay single characters, so generic argument nesting can be counted.
const TWO_CHAR_PUNCT = new Set(['=>', '==', '!=', '+=', '-=', '*=', '/=', '%=', '&=', '|=', '^=', '??', '?.', '&&', '||', '::', '++', '--', '->']);

/**
 * @typedef {object} SourceAnalysis
 * @property {Array<{ name: string, category: NamingCategory, style: string }>} fields
 * @property {number} serializedPrivate  Private instance fields with `[SerializeField]`.
 * @property {number} publicInstance     Public instance fields Unity would serialize instead.
 * @property {number} allman
 * @property {number} knr
 * @property {boolean} namespaceUsed
 */

/**
 * @param {string} text
 * @returns {SourceAnalysis}
 */
export function analyzeSource(text) {
  const tokens = tokenizeCSharp(text);
  /** @type {SourceAnalysis} */
  const analysis = { fields: [], serializedPrivate: 0, publicInstance: 0, allman: 0, knr: 0, namespaceUsed: false };
  /** @type {Array<{ kind: string, typeKind?: string, saved?: Token[] }>} */
  const stack = [{ kind: 'namespace' }];
  /** @type {Token[]} */
  let current = [];

  for (let index = 0; index < tokens.length; index += 1) {
    const token = tokens[index];
    const top = stack[stack.length - 1];
    if (token.value === '{') {
      countBraceStyle(tokens, index, analysis);
      if (top.kind === 'type' && current.some((item) => item.value === '=')) {
        stack.push({ kind: 'initializer', saved: current });
      } else {
        stack.push(getBlockScope(current, analysis));
      }
      current = [];
      continue;
    }
    if (token.value === '}') {
      const popped = stack.length > 1 ? stack.pop() : null;
      current = popped?.kind === 'initializer' ? (popped.saved ?? []) : [];
      continue;
    }
    if (token.value === ';') {
      if (top.kind === 'type' && isFieldScope(top.typeKind)) analyzeStatement(current, analysis);
      else if (top.kind === 'namespace' && current[0]?.value === 'namespace') analysis.namespaceUsed = true;
      current = [];
      continue;
    }
    if (top.kind === 'namespace' || top.kind === 'type') current.push(token);
  }
  return analysis;
}

/**
 * @param {string | undefined} typeKind
 * @returns {boolean}
 */
function isFieldScope(typeKind) {
  return typeKind === 'class' || typeKind === 'struct' || typeKind === 'record';
}

/**
 * @param {Token[]} header
 * @param {SourceAnalysis} analysis
 * @returns {{ kind: string, typeKind?: string }}
 */
function getBlockScope(header, analysis) {
  const parenIndex = header.findIndex((token) => token.value === '(');
  const typeIndex = header.findIndex((token) => token.type === 'ident' && TYPE_KEYWORDS.has(token.value));
  if (typeIndex !== -1 && (parenIndex === -1 || typeIndex < parenIndex)) {
    const keyword = header[typeIndex].value;
    return { kind: 'type', typeKind: keyword === 'record' ? 'record' : keyword };
  }
  if (header[0]?.value === 'namespace') {
    analysis.namespaceUsed = true;
    return { kind: 'namespace' };
  }
  return { kind: 'code' };
}

/**
 * Allman puts the brace on its own line; K&R keeps it on the line before. One-line blocks such as
 * `{ get; set; }` are not counted.
 * @param {Token[]} tokens
 * @param {number} index
 * @param {SourceAnalysis} analysis
 */
function countBraceStyle(tokens, index, analysis) {
  const previous = tokens[index - 1];
  const next = tokens[index + 1];
  if (!previous || !next || next.line === tokens[index].line) return;
  if (previous.line < tokens[index].line) analysis.allman += 1;
  else analysis.knr += 1;
}

/**
 * @param {Token[]} statement
 * @param {SourceAnalysis} analysis
 */
function analyzeStatement(statement, analysis) {
  let index = 0;
  /** @type {string[]} */
  const attributes = [];
  while (statement[index]?.value === '[') {
    const end = findClosing(statement, index, '[', ']');
    for (const token of statement.slice(index + 1, end)) {
      if (token.type === 'ident') attributes.push(token.value);
    }
    index = end + 1;
  }

  /** @type {Set<string>} */
  const modifiers = new Set();
  while (statement[index] && statement[index].type === 'ident' && MODIFIERS.has(statement[index].value)) {
    modifiers.add(statement[index].value);
    index += 1;
  }
  if (modifiers.has('event') || modifiers.has('fixed') || modifiers.has('extern') || modifiers.has('abstract')) return;

  const rest = statement.slice(index);
  if (rest.length < 2) return;
  const assignIndex = rest.findIndex((token) => token.value === '=');
  const declaration = assignIndex === -1 ? rest : rest.slice(0, assignIndex);
  if (declaration.some((token) => token.value === '=>')) return;
  if (declaration.some((token) => token.type === 'ident' && NON_FIELD_KEYWORDS.has(token.value))) return;
  if (hasCallParenthesis(declaration)) return;

  const names = collectDeclaratorNames(declaration);
  if (names.length === 0) return;

  const isConst = modifiers.has('const');
  const isStatic = modifiers.has('static') || isConst;
  const isReadonly = modifiers.has('readonly');
  const isShared = modifiers.has('public') || modifiers.has('protected') || modifiers.has('internal');
  if (modifiers.has('public') && !isStatic && !isReadonly && !attributes.includes('NonSerialized')) analysis.publicInstance += names.length;

  /** @type {NamingCategory | null} */
  const category = isConst || (isStatic && isReadonly) ? 'constants' : isShared ? null : isStatic ? 'privateStatic' : 'privateInstance';
  if (!category) return;
  if (category === 'privateInstance' && attributes.includes('SerializeField')) analysis.serializedPrivate += names.length;
  for (const name of names) analysis.fields.push({ name, category, style: classifyFieldName(name) });
}

/**
 * @param {Token[]} declaration
 * @returns {boolean} True for methods, constructors and other members with an argument list.
 */
function hasCallParenthesis(declaration) {
  return declaration.some((token, index) => {
    if (token.value !== '(' || index === 0) return false;
    const previous = declaration[index - 1];
    return previous.type === 'ident' || previous.value === '>';
  });
}

/**
 * @param {Token[]} declaration
 * @returns {string[]} Declared field names, ignoring type arguments, array ranks and tuple members.
 */
function collectDeclaratorNames(declaration) {
  /** @type {string[]} */
  const names = [];
  let angle = 0;
  let paren = 0;
  let bracket = 0;
  for (let index = 0; index < declaration.length; index += 1) {
    const token = declaration[index];
    if (token.value === '<') angle += 1;
    else if (token.value === '>') angle = Math.max(0, angle - 1);
    else if (token.value === '(') paren += 1;
    else if (token.value === ')') paren = Math.max(0, paren - 1);
    else if (token.value === '[') bracket += 1;
    else if (token.value === ']') bracket = Math.max(0, bracket - 1);
    if (angle > 0 || paren > 0 || bracket > 0 || token.type !== 'ident' || index === 0) continue;
    const next = declaration[index + 1];
    if (!next || next.value === ',') names.push(token.value);
  }
  return names;
}

/**
 * @param {string} name
 * @returns {string} A style id from STYLE_LABELS.
 */
export function classifyFieldName(name) {
  if (/^m_[a-z0-9]/.test(name)) return 'm_camel';
  if (/^m_[A-Z]/.test(name)) return 'm_Pascal';
  if (/^s_[a-z0-9]/.test(name)) return 's_camel';
  if (/^s_[A-Z]/.test(name)) return 's_Pascal';
  if (/^k_[A-Z]/.test(name)) return 'k_Pascal';
  if (/^k_[a-z0-9]/.test(name)) return 'k_camel';
  if (/^[A-Z][A-Z0-9]*(_[A-Z0-9]+)+$/.test(name) || /^[A-Z][A-Z0-9]{2,}$/.test(name)) return 'UPPER_SNAKE';
  if (/^_[a-z][A-Za-z0-9]*$/.test(name)) return '_camel';
  if (/^[a-z][A-Za-z0-9]*$/.test(name)) return 'camel';
  if (/^[A-Z][A-Za-z0-9]*$/.test(name)) return 'Pascal';
  return 'other';
}

/**
 * @param {string} text
 * @returns {boolean}
 */
export function isGeneratedSource(text) {
  return GENERATED_HEADER.test(text.slice(0, 2000));
}

/**
 * The folder shown per naming group: at most three path segments, for example `Assets/Game/Combat`.
 * @param {string} relativePath
 * @returns {string}
 */
export function getNamingFolder(relativePath) {
  return relativePath.split('/').slice(0, -1).slice(0, 3).join('/');
}

/**
 * An evenly spaced sample, so one alphabetically early folder cannot take the whole budget.
 * @param {string[]} paths  Sorted.
 * @param {number} [max]
 * @returns {string[]}
 */
export function selectNamingSample(paths, max = MAX_NAMING_SAMPLE_FILES) {
  if (paths.length <= max) return [...paths];
  const step = paths.length / max;
  return Array.from({ length: max }, (_, position) => paths[Math.floor(position * step)]);
}

/**
 * @typedef {object} CategorySummary
 * @property {string} dominant     A style id, or `mixed`.
 * @property {string} label
 * @property {string | null} topStyle
 * @property {number} share        0-1, rounded to three decimals.
 * @property {number} sampleSize
 * @property {'sample' | 'editorconfig'} source
 */

/**
 * @typedef {object} NamingFact
 * @property {number} files
 * @property {Record<NamingCategory, CategorySummary>} categories
 * @property {{ allman: number, knr: number, dominant: 'Allman' | 'K&R' | 'mixed' }} braces
 * @property {{ files: number, share: number }} namespaces
 * @property {{ serialized: number, publicFields: number, share: number | null }} serializeField
 * @property {Array<{ folder: string, files: number, dominant: string, label: string, share: number, sampleSize: number }>} folders
 */

/**
 * @returns {{ add: (relativePath: string, text: string) => void, result: (options?: { editorconfig?: EditorconfigNaming | null }) => NamingFact }}
 */
export function createNamingCollector() {
  /** @type {Record<NamingCategory, Map<string, number>>} */
  const counts = { privateInstance: new Map(), privateStatic: new Map(), constants: new Map() };
  /** @type {Map<string, { files: number, styles: Map<string, number> }>} */
  const folders = new Map();
  let files = 0;
  let allman = 0;
  let knr = 0;
  let namespaceFiles = 0;
  let serialized = 0;
  let publicFields = 0;

  return {
    add(relativePath, text) {
      const analysis = analyzeSource(text);
      files += 1;
      allman += analysis.allman;
      knr += analysis.knr;
      serialized += analysis.serializedPrivate;
      publicFields += analysis.publicInstance;
      if (analysis.namespaceUsed) namespaceFiles += 1;
      const folderKey = getNamingFolder(relativePath);
      const folder = folders.get(folderKey) ?? { files: 0, styles: new Map() };
      folder.files += 1;
      folders.set(folderKey, folder);
      for (const field of analysis.fields) {
        increment(counts[field.category], field.style);
        if (field.category === 'privateInstance') increment(folder.styles, field.style);
      }
    },
    result({ editorconfig = null } = {}) {
      return {
        files,
        categories: {
          privateInstance: summarizeCategory(counts.privateInstance, editorconfig?.privateInstance),
          privateStatic: summarizeCategory(counts.privateStatic, editorconfig?.privateStatic),
          constants: summarizeCategory(counts.constants, editorconfig?.constants),
        },
        braces: { allman, knr, dominant: pickBraceStyle(allman, knr) },
        namespaces: { files: namespaceFiles, share: files ? round(namespaceFiles / files) : 0 },
        serializeField: {
          serialized,
          publicFields,
          share: serialized + publicFields > 0 ? round(serialized / (serialized + publicFields)) : null,
        },
        folders: summarizeFolders(folders),
      };
    },
  };
}

/**
 * @param {Map<string, number>} counts
 * @param {{ style: string, label: string } | undefined | null} override
 * @returns {CategorySummary}
 */
export function summarizeCategory(counts, override = null) {
  const entries = [...counts].sort((a, b) => b[1] - a[1] || compareOrdinal(a[0], b[0]));
  const sampleSize = entries.reduce((total, [, count]) => total + count, 0);
  const topStyle = entries[0]?.[0] ?? null;
  const share = sampleSize > 0 && entries[0] ? entries[0][1] / sampleSize : 0;
  if (override) {
    return { dominant: override.style, label: override.label, topStyle, share: round(share), sampleSize, source: 'editorconfig' };
  }
  const dominant = sampleSize >= MIN_NAMING_SAMPLE && share >= DOMINANT_SHARE && topStyle ? topStyle : 'mixed';
  return { dominant, label: STYLE_LABELS[dominant] ?? dominant, topStyle, share: round(share), sampleSize, source: 'sample' };
}

/**
 * @param {Map<string, { files: number, styles: Map<string, number> }>} folders
 * @returns {NamingFact['folders']}
 */
function summarizeFolders(folders) {
  return [...folders]
    .sort((a, b) => b[1].files - a[1].files || compareOrdinal(a[0], b[0]))
    .slice(0, MAX_NAMING_FOLDERS)
    .map(([folder, value]) => {
      const summary = summarizeCategory(value.styles);
      return { folder, files: value.files, dominant: summary.dominant, label: summary.label, share: summary.share, sampleSize: summary.sampleSize };
    });
}

/**
 * @param {number} allman
 * @param {number} knr
 * @returns {'Allman' | 'K&R' | 'mixed'}
 */
function pickBraceStyle(allman, knr) {
  const total = allman + knr;
  if (total === 0) return 'mixed';
  if (allman / total >= DOMINANT_SHARE) return 'Allman';
  return knr / total >= DOMINANT_SHARE ? 'K&R' : 'mixed';
}

/**
 * @typedef {Partial<Record<NamingCategory, { style: string, label: string, rule: string }>>} EditorconfigNaming
 */

/**
 * Naming rules from an `.editorconfig`, which are authoritative over the sample.
 * @param {string} text
 * @returns {EditorconfigNaming}
 */
export function parseEditorconfigNaming(text) {
  /** @type {Map<string, string>} */
  const settings = new Map();
  let applies = false;
  for (const rawLine of text.split(/\r?\n/)) {
    const line = rawLine.trim();
    if (!line || line.startsWith('#') || line.startsWith(';')) continue;
    const section = /^\[(.+)]$/.exec(line);
    if (section) {
      applies = sectionAppliesToCSharp(section[1]);
      continue;
    }
    if (!applies) continue;
    const separator = line.indexOf('=');
    if (separator === -1) continue;
    settings.set(line.slice(0, separator).trim().toLowerCase(), line.slice(separator + 1).trim());
  }

  /** @type {Array<{ rule: string, category: NamingCategory, exact: boolean, privateOnly: boolean, style: { style: string, label: string } }>} */
  const rules = [];
  for (const [key, value] of settings) {
    const match = /^dotnet_naming_rule\.([^.]+)\.symbols$/.exec(key);
    if (!match) continue;
    const rule = match[1];
    if ((settings.get(`dotnet_naming_rule.${rule}.severity`) ?? '').toLowerCase() === 'none') continue;
    const styleName = settings.get(`dotnet_naming_rule.${rule}.style`);
    if (!styleName) continue;
    const symbol = value.trim();
    const kinds = splitList(settings.get(`dotnet_naming_symbols.${symbol}.applicable_kinds`) ?? '*');
    const accessibilities = splitList(settings.get(`dotnet_naming_symbols.${symbol}.applicable_accessibilities`) ?? '*');
    const modifiers = splitList(settings.get(`dotnet_naming_symbols.${symbol}.required_modifiers`) ?? '');
    if (!kinds.includes('field') && !kinds.includes('*')) continue;
    if (!accessibilities.includes('private') && !accessibilities.includes('*')) continue;
    const style = readEditorconfigStyle(settings, styleName);
    if (!style) continue;
    const privateOnly = !accessibilities.includes('*');
    for (const { category, exact } of matchCategories(modifiers)) rules.push({ rule, category, exact, privateOnly, style });
  }

  /** @type {EditorconfigNaming} */
  const naming = {};
  for (const category of NAMING_CATEGORIES) {
    const candidates = rules.filter((item) => item.category === category);
    const best =
      candidates.find((item) => item.exact && item.privateOnly) ??
      candidates.find((item) => item.exact) ??
      candidates.find((item) => item.privateOnly) ??
      candidates[0];
    if (best) naming[category] = { style: best.style.style, label: best.style.label, rule: best.rule };
  }
  return naming;
}

/**
 * @param {string[]} modifiers
 * @returns {Array<{ category: NamingCategory, exact: boolean }>}
 */
function matchCategories(modifiers) {
  const set = new Set(modifiers);
  if (set.has('const')) return [{ category: 'constants', exact: true }];
  if (set.has('static') && set.has('readonly')) return [{ category: 'constants', exact: true }];
  if (set.has('static')) return [{ category: 'privateStatic', exact: true }];
  if (set.has('readonly')) return [{ category: 'privateInstance', exact: true }];
  if (set.size > 0) return [];
  // A symbol group with no required modifiers matches every field.
  return NAMING_CATEGORIES.map((category) => ({ category, exact: false }));
}

/**
 * @param {Map<string, string>} settings
 * @param {string} styleName
 * @returns {{ style: string, label: string } | null}
 */
function readEditorconfigStyle(settings, styleName) {
  const name = styleName.trim();
  const prefix = settings.get(`dotnet_naming_style.${name}.required_prefix`) ?? '';
  const capitalization = (settings.get(`dotnet_naming_style.${name}.capitalization`) ?? '').toLowerCase();
  if (!capitalization) return null;
  const style = EDITORCONFIG_STYLES[`${prefix}|${capitalization}`];
  if (style) return { style, label: STYLE_LABELS[style] ?? style };
  return { style: 'other', label: prefix ? `${prefix} + ${capitalization}` : capitalization };
}

/** @type {Record<string, string>} */
const EDITORCONFIG_STYLES = {
  'm_|camel_case': 'm_camel',
  'm_|pascal_case': 'm_Pascal',
  's_|camel_case': 's_camel',
  's_|pascal_case': 's_Pascal',
  'k_|pascal_case': 'k_Pascal',
  'k_|camel_case': 'k_camel',
  '_|camel_case': '_camel',
  '|camel_case': 'camel',
  '|pascal_case': 'Pascal',
  '|all_upper': 'UPPER_SNAKE',
};

/**
 * @param {string} glob
 * @returns {boolean}
 */
function sectionAppliesToCSharp(glob) {
  const value = glob.trim();
  if (value === '*' || value === '**') return true;
  if (/\.cs$/i.test(value)) return true;
  return /\.\{[^}]*\bcs\b[^}]*\}$/i.test(value);
}

/**
 * @param {string} value
 * @returns {string[]}
 */
function splitList(value) {
  return value
    .split(',')
    .map((item) => item.trim().toLowerCase())
    .filter(Boolean);
}

/**
 * @param {Map<string, number>} counts
 * @param {string} key
 */
function increment(counts, key) {
  counts.set(key, (counts.get(key) ?? 0) + 1);
}

/**
 * @param {number} value
 * @returns {number}
 */
function round(value) {
  return Math.round(value * 1000) / 1000;
}

/**
 * @param {Token[]} tokens
 * @param {number} start
 * @param {string} open
 * @param {string} close
 * @returns {number} Index of the closing token, or the last index when it never closes.
 */
function findClosing(tokens, start, open, close) {
  let depth = 0;
  for (let index = start; index < tokens.length; index += 1) {
    if (tokens[index].value === open) depth += 1;
    else if (tokens[index].value === close) {
      depth -= 1;
      if (depth === 0) return index;
    }
  }
  return tokens.length - 1;
}

/**
 * @param {string} text
 * @param {number} index
 * @returns {boolean}
 */
function isStringStart(text, index) {
  let position = index;
  while (text[position] === '$' || text[position] === '@') position += 1;
  return text[position] === '"';
}

/**
 * Handles plain, verbatim, interpolated and raw string literals.
 * @param {string} text
 * @param {number} start
 * @returns {number} Index just after the literal.
 */
function skipStringLiteral(text, start) {
  let index = start;
  let interpolated = false;
  let verbatim = false;
  while (text[index] === '$' || text[index] === '@') {
    if (text[index] === '$') interpolated = true;
    else verbatim = true;
    index += 1;
  }
  if (text.startsWith('"""', index)) return skipRawString(text, index);
  index += 1;
  let braces = 0;
  while (index < text.length) {
    const char = text[index];
    if (braces > 0) {
      if (char === '{') braces += 1;
      else if (char === '}') braces -= 1;
      else if (isStringStart(text, index)) {
        index = skipStringLiteral(text, index);
        continue;
      } else if (char === "'") {
        index = skipCharLiteral(text, index);
        continue;
      }
      index += 1;
      continue;
    }
    if (!verbatim && char === '\\') {
      index += 2;
      continue;
    }
    if (verbatim && char === '"' && text[index + 1] === '"') {
      index += 2;
      continue;
    }
    if (char === '"') return index + 1;
    if (interpolated && (char === '{' || char === '}')) {
      if (text[index + 1] === char) {
        index += 2;
        continue;
      }
      if (char === '{') braces = 1;
      index += 1;
      continue;
    }
    if (!verbatim && char === '\n') return index;
    index += 1;
  }
  return index;
}

/**
 * @param {string} text
 * @param {number} start  Index of the first quote.
 * @returns {number}
 */
function skipRawString(text, start) {
  let quotes = 0;
  while (text[start + quotes] === '"') quotes += 1;
  const fence = '"'.repeat(quotes);
  const end = text.indexOf(fence, start + quotes);
  if (end === -1) return text.length;
  let after = end + quotes;
  while (text[after] === '"') after += 1;
  return after;
}

/**
 * @param {string} text
 * @param {number} start
 * @returns {number}
 */
function skipCharLiteral(text, start) {
  let index = start + 1;
  while (index < text.length) {
    if (text[index] === '\\') index += 2;
    else if (text[index] === "'") return index + 1;
    else if (text[index] === '\n') return index;
    else index += 1;
  }
  return index;
}

/**
 * @param {string} text
 * @param {number} index
 * @returns {number}
 */
function endOfLine(text, index) {
  const newline = text.indexOf('\n', index);
  return newline === -1 ? text.length : newline;
}

/**
 * @param {string} text
 * @param {number} start
 * @param {number} end
 * @returns {number}
 */
function countNewlines(text, start, end) {
  let count = 0;
  for (let index = start; index < end; index += 1) {
    if (text[index] === '\n') count += 1;
  }
  return count;
}

/**
 * @param {string} char
 * @returns {boolean}
 */
function isIdentifierStart(char) {
  return /[A-Za-z_]/.test(char);
}

/**
 * @param {string} char
 * @returns {boolean}
 */
function isIdentifierPart(char) {
  return /[A-Za-z0-9_]/.test(char);
}
